#!/usr/bin/env python3

from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('welcome.html')

@app.route('/federation')
def federation():
    return render_template('welcome_kirk.html')

if __name__ == '__main__':
    app.run(port=3001, host="172.17.0.1")

