#!/usr/bin/env python3

from flask import Flask, render_template

app = Flask(__name__)

# Add another route for bridge (only commanders can access it. Sorry Bones!)

@app.route('/')
def index():
    return render_template('welcome.html')

if __name__ == '__main__':
    app.run(port=3001, host="127.0.0.1")

    #app.run(ssl_context=('/home/rahul/my_certs/pomerium.rahultoppur.com.crt', '/home/rahul/my_certs/rahul_key.pem'),
    #    port=443, host="192.168.0.80")
